[build]
builder = "NIXPACKS"

[deploy]
startCommand = "echo 'This is a multi-service app. Deploy backend and frontend separately.'"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"